name: Sirani McNeill
bio: 'Blockchain and Cyber Security Software Engineer'
description: Sirani McNeill
external-image: true
picture:   /https://twitter.com/JobseekerSirani/photo
resume: true
resume-external: true
resume-url: 
url: 'http://siranimcneillportfolio.github.io
permalink: '/:title/'
twitter: jobseekersirani
linkedin: sirani-m
github: mcne65
email: siranimcneill020@gmail.com
authors:
  siranimcneill:
    name: Sirani McNeill
    bio: 'Blockchain and Cyber Security Software Engineer'
    external-image: 'false'
    picture: >-
      /https://twitter.com/JobseekerSirani/photo
    twitter: jobseekersirani
>>>>>>> Stashed changes
width: normal
about: true
blog: true
read-time: true
show-tags: true
related: true
post-advance-links:
  - blog
show-author: true
animation: true
plugins_dir:
  - jekyll-seo-tag
  - jekyll-gist
  - jekyll-feed
  - jemoji
jekyll-mentions:
  base_url: 'https://github.com'
